version: "3.8"

services:
  app:
    build: .
    container_name: smart-ceipal-app
    ports:
      - "8000:8000"
    volumes:
      # Mount resources directory to persist screenshots and logs
      - ./resources:/smart_ceipal/resources
      # Mount drivers directory to persist ChromeDriver
      - ./drivers:/smart_ceipal/drivers
    restart: always
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5' 